### ISSUE TITLE
ICU Ownership Takeover Request

### ISSUE THREAD

**Issue by TheCoolOne123** [hwdotexe/iControlU#3]
As most people know, development of ICU stopped a year ago. And the plugin itself has been dormant for over a few years now on Spigot. In the premium case, it had even gotten removed. 

I'd like to takeover the plugins and take care of it, and give the fun it brought back to the Minecraft community. Of course for this, I want to ask your oermissikn. Since this is still your work 😅

**Comment by TheCoolOne123** [comment]
Excuse my bad English, I'm typing this on my phone and doing this whilr walking home.

I've made an mcm post for people's opinions:
https://www.mc-market.org/threads/689909

**Comment by hwdotexe** [comment]
Hi @TheCoolOne123 ,

Thanks for reaching out about iControlU! Indeed, I've moved on from Minecraft plugin development (with some few exceptions), so iControlU is no longer actively maintained. As part of this decision, this repository was created so others can contribute to its continued growth if they choose to do so. iControlU is no longer a premium resource, and I welcome any input that other developers wish to provide.

With that being said, I am retaining ownership of the plugin for all intents and purposes. However, if you are interested in picking up the maintenance of the plugin, you are welcome to Fork this repository and submit Pull Requests with changes you think are valuable. I will happily look at them and merge them in. Otherwise, you have the freedom to maintain and distribute your own fork of the plugin as you see fit, as specified in the `LICENSE` file. 

The codebase has definitely aged, and the code itself is probably not well optimized - let alone for newer versions of the game. Nevertheless, I am certain it can be updated to work on 1.18.x (the latest version of the game at the time of writing).

I hope this answers your question. Happy coding!

**Comment by TheCoolOne123** [comment]
In the best case senario, I'd do a "iControlU: Reloaded" case, but before I'd do. I wanted to make sure that's ok. Since I'd be giving it under my name('s). 

Otherwise, I could also just rewrite an entire plugin. However, I do wanna keep the glory the old plugin had.

**Comment by TheCoolOne123** [comment]
@hwdotexe 
I'll try to update the code, if I'm unsuccessful in doing so. I'll create it from scratch. 
Thanks for making our lives as server admins enjoyable!
